services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 1
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  gradio:
    build:
      context: .
      dockerfile: Dockerfile
    command: python gradio_app.py
    ports:
      - "7860:7860"
    environment:
      - API_BASE=http://api:8000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - api
