version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
root:
  handlers: [console]
  level: INFO
loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: False
  chromadb:
    handlers: [console]
    level: INFO
    propagate: False
